### ISSUE TITLE
Node dist/index.js throws error about import statement

### ISSUE THREAD

**Issue by kluplau** [v2xnetwork/typescript-express-typeorm-boilerplate#5]
Hi,

Sorry to bother you with this kinda old repo, but it really has potential! Great work.

**Replicate**
- Setup: Nodemon has some dependencies that act up, so run `npm install nodemon@latest` to fix that.  Other than that your guide in README works.
- Build and run: Run `npm run build` and `node dist/index.js`.

**Error**
![image](https://user-images.githubusercontent.com/1536598/74098543-ca636a80-4b19-11ea-99f4-e28c323c692c.png)

Looking at the error, it seems like TypeScript haven't transpiled the code, but if you look at the generated code, you see that there isn't any import statement at alle.

**Comment by kluplau** [comment]
The issue can be resolved with editing the typeorm config.

https://stackoverflow.com/questions/58148222/nodejs-problems-with-imports-when-transpiling-from-typescript/58177098#58177098

**Comment by shumailxyz** [comment]
Hi,

Unfortunately I am unable to maintain this repo due to lack of time. We have been mainly using NestJS for a while and quite happy with it.

Can you please create a PR with fix for this import error?
